name: postgres-db
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres1234
    volumes:
      - ./data:/var/lib/postgresql/data